#!/usr/bin/env bash
set -euo pipefail

TEST_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PROJECT_ROOT=$(CDPATH= cd -- "$TEST_ROOT/.." && pwd)
FIXTURE=$TEST_ROOT/fixtures/matte-black.colors.toml
REFERENCE=/usr/share/omarchy/themes/matte-black/colors.toml
TEMP_ROOT=$(mktemp -d)
trap 'rm -rf -- "$TEMP_ROOT"' EXIT HUP INT TERM

fake_bin=$TEMP_ROOT/bin
fake_home=$TEMP_ROOT/home
user_themes=$fake_home/.config/omarchy/themes
stock_themes=$TEMP_ROOT/stock/themes
bb_theme_dir=$TEMP_ROOT/bb-theme
mkdir -p "$fake_bin" "$user_themes/matte-black" "$stock_themes/matte-black" "$bb_theme_dir"
if [ -f "$REFERENCE" ]; then cp "$REFERENCE" "$stock_themes/matte-black/colors.toml"; else cp "$FIXTURE" "$stock_themes/matte-black/colors.toml"; fi

cat >"$fake_bin/bb" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
case ${1:-}:${2:-} in
  theme:dir) printf '%s\n' "${FAKE_BB_THEME_DIR:?}" ;;
  theme:set) printf '%s\n' "$3" >"${FAKE_BB_THEME_DIR:?}/active" ;;
  theme:show) printf 'Active: Test (default)\n' ;;
  *) exit 2 ;;
esac
EOF
cat >"$fake_bin/omarchy" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
[ "${1:-}" = theme ] && [ "${2:-}" = current ] && printf '%s\n' 'Matte Black'
EOF
chmod +x "$fake_bin/bb" "$fake_bin/omarchy"

export HOME=$fake_home PATH=$fake_bin:$PATH
export FAKE_BB_THEME_DIR=$bb_theme_dir
export BB_BIN=$fake_bin/bb
export BB_CLI=''
export OMARCHY_USER_THEME_ROOT=$user_themes
export OMARCHY_STOCK_THEME_ROOT=$stock_themes

command=$PROJECT_ROOT/bin/omarchy-bb-theme-sync
bash -n "$command" "$PROJECT_ROOT/install.sh" "$PROJECT_ROOT/uninstall.sh" \
  "$PROJECT_ROOT/hooks/theme-set.d/omarchy-bb-theme-sync" "$0"

dry_css=$TEMP_ROOT/dry.css
"$command" --dry-run matte-black >"$dry_css"
grep -q '^:root, \.light {' "$dry_css"
grep -q '^\.dark {' "$dry_css"
grep -q -- '--canvas: #ececec;' "$dry_css"
grep -q -- '--canvas: #121212;' "$dry_css"
grep -q -- '--primary: #e68e0d;' "$dry_css"
grep -q -- '--ansi-15:' "$dry_css"

"$command" sync matte-black >/dev/null
generated=$bb_theme_dir/omarchy-sync/theme.css
[ -s "$generated" ]
grep -q 'Generated by omarchy-bb-theme-sync' "$generated"
[ "$(cat "$bb_theme_dir/active")" = omarchy-sync ]

# When no normal `bb` command exists, discover the CLI exposed by a running
# BB AppImage mount. The override keeps this test isolated from a real mount.
appimage_temp=$TEMP_ROOT/appimage-temp
appimage_bb=$appimage_temp/.mount_bb-theme-sync/resources/app.asar.unpacked/node_modules/bb-app/host-daemon/dist/bb
mkdir -p "$(dirname "$appimage_bb")"
cp "$fake_bin/bb" "$appimage_bb"
chmod +x "$appimage_bb"
PATH=/usr/bin:/bin BB_BIN='' OMARCHY_BB_APP_DATA_ROOT=$TEMP_ROOT/no-installed OMARCHY_BB_APPIMAGE_TMP_ROOT=$appimage_temp "$command" sync matte-black >/dev/null
[ "$(cat "$bb_theme_dir/active")" = omarchy-sync ]

# After an update, packaged BB keeps its CLI inside a versioned extracted app
# directory rather than a live AppImage mount. Discover that layout too.
packaged_bb=$fake_home/.local/share/bb-0.42.1/resources/app.asar.unpacked/node_modules/bb-app/host-daemon/dist/bb
mkdir -p "$(dirname "$packaged_bb")"
cp "$fake_bin/bb" "$packaged_bb"
chmod +x "$packaged_bb"
PATH=/usr/bin:/bin BB_BIN='' BB_CLI='' OMARCHY_BB_APP_DATA_ROOT=$fake_home/.local/share OMARCHY_BB_APPIMAGE_TMP_ROOT=$TEMP_ROOT/no-mount "$command" sync matte-black >/dev/null
[ "$(cat "$bb_theme_dir/active")" = omarchy-sync ]

# User themes take precedence over stock themes.
cat >"$user_themes/matte-black/colors.toml" <<'EOF'
mode = "light"
background = "#fafafa"
foreground = "#111111"
accent = "#123456"
EOF
"$command" sync matte-black --no-activate >/dev/null
grep -q -- '--canvas: #fafafa;' "$generated"
grep -q -- '--primary: #123456;' "$generated"

# No slug uses the current Omarchy theme, as the installed hook does.
rm -f "$user_themes/matte-black/colors.toml"
"$PROJECT_ROOT/hooks/theme-set.d/omarchy-bb-theme-sync" matte-black >/dev/null
[ "$(cat "$bb_theme_dir/active")" = omarchy-sync ]

# Install and uninstall only touch the isolated test HOME.
HOME=$fake_home "$PROJECT_ROOT/install.sh" >/dev/null
[ -L "$fake_home/.local/bin/omarchy-bb-theme-sync" ]
[ -L "$fake_home/.config/omarchy/hooks/theme-set.d/omarchy-bb-theme-sync" ]
status_output=$(HOME=$fake_home "$fake_home/.local/bin/omarchy-bb-theme-sync" status)
grep -q "Project: $PROJECT_ROOT" <<<"$status_output"
HOME=$fake_home "$PROJECT_ROOT/uninstall.sh" >/dev/null
[ ! -e "$fake_home/.local/bin/omarchy-bb-theme-sync" ]
[ ! -e "$fake_home/.config/omarchy/hooks/theme-set.d/omarchy-bb-theme-sync" ]
HOME=$fake_home "$PROJECT_ROOT/uninstall.sh" --remove-theme >/dev/null
[ ! -e "$generated" ]

printf '%s\n' 'verification: PASS (bash syntax, dry-run CSS, source precedence, activation, packaged/AppImage discovery, symlink status, hook)'
